-- Import recorded CSV shots from recorded data/
-- Generated by scripts/generate_recorded_shots_sql.py — re-run that script after CSV edits.
-- Safe to re-run: skips a game if its first CSV timestamp already exists on a shot.
-- Attaches to schedule games when present; otherwise creates the game.

do $$
declare
  brighton uuid;
  season uuid;
  opp uuid;
  gid uuid;
  tid uuid;
  pid uuid;
  apid uuid;
  n int;
begin
  select id into brighton from public.teams where is_brighton limit 1;
  select id into season from public.seasons where label = '2026 Fall' limit 1;
  if brighton is null or season is null then
    raise exception 'Run schema.sql first';
  end if;

  -- ===== Morgan 2026-08-17 (27 shots) =====
  insert into public.teams (name, is_brighton) values ('Morgan', false)
  on conflict (name) do nothing;
  select id into opp from public.teams where name = 'Morgan';

  select g.id into gid from public.games g
  where g.season_id = season and g.date = '2026-08-17'
    and g.home_team_id = opp and g.away_team_id = brighton
  limit 1;
  if gid is null then
    insert into public.games (season_id, date, game_type, home_team_id, away_team_id, our_team_id)
    values (season, '2026-08-17', 'preseason', opp, brighton, brighton)
    returning id into gid;
  end if;

  select count(*) into n from public.shots
  where game_id = gid and created_at = '2026-08-17T23:15:26.914Z'::timestamptz;
  if n > 0 then
    raise notice 'Morgan shots already imported — skipping';
  else

    -- 2026-08-17T21:38:11.780Z us #5 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '5'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '5',
      7, 11.2, 'LW-BOX', 'Left wide · Penalty area', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T21:38:11.780Z'::timestamptz
    );

    -- 2026-08-17T21:38:21.007Z us #32 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '32',
      39.7, 4.7, 'C-6Y', 'Six-yard box · Center', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T21:38:21.007Z'::timestamptz
    );

    -- 2026-08-17T21:38:48.184Z us #32 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '32',
      42.7, 21.3, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T21:38:48.184Z'::timestamptz
    );

    -- 2026-08-17T21:39:51.895Z us #32 Shot on Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '32',
      33.6, 8.3, 'C-PS', 'Box · Center', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-17T21:39:51.895Z'::timestamptz
    );

    -- 2026-08-17T21:40:01.021Z us #26 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '26'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '26',
      30.9, 2.3, 'C-6Y', 'Six-yard box · Center', 'goal',
      apid, null, null, null, null, null,
      '2026-08-17T21:40:01.021Z'::timestamptz
    );

    -- 2026-08-17T21:47:42.653Z us #13 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '13'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '13',
      39.3, 12.1, 'C-BOX', 'Box · Center', 'goal',
      apid, null, null, null, null, null,
      '2026-08-17T21:47:42.653Z'::timestamptz
    );

    -- 2026-08-17T21:49:11.124Z us #2 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '2'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '2',
      54.6, 21.9, 'RW-D', 'Right wide · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T21:49:11.124Z'::timestamptz
    );

    -- 2026-08-17T21:52:01.751Z us #26 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '26'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '26',
      21.2, 19.3, 'LHS-D', 'Left half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T21:52:01.751Z'::timestamptz
    );

    -- 2026-08-17T21:56:40.921Z us #17 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '17'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '17',
      0, 0, 'LW-6Y', 'Left wide · Six-yard', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T21:56:40.921Z'::timestamptz
    );

    -- 2026-08-17T21:57:52.536Z us #24 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '24'
    limit 1;
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '24',
      36.2, 8.1, 'C-PS', 'Box · Center', 'goal',
      apid, 'pass', 47.4, 3, 'RHS-6Y', 'Box · Right half-space',
      '2026-08-17T21:57:52.536Z'::timestamptz
    );

    -- 2026-08-17T22:00:31.048Z us #8 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '8',
      48.5, 22, 'RHS-D', 'Right half-space · Top of the box', 'goal',
      apid, null, null, null, null, null,
      '2026-08-17T22:00:31.048Z'::timestamptz
    );

    -- 2026-08-17T22:02:51.493Z us #8 Shot Blocked
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '8',
      48.4, 13.7, 'RHS-BOX', 'Box · Right half-space', 'blocked',
      apid, null, null, null, null, null,
      '2026-08-17T22:02:51.493Z'::timestamptz
    );

    -- 2026-08-17T22:05:27.955Z us #8 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '8',
      48.5, 10.2, 'RHS-PS', 'Box · Right half-space', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:05:27.955Z'::timestamptz
    );

    -- 2026-08-17T22:06:51.541Z us #29 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '29'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '29',
      45, 11.2, 'RHS-BOX', 'Box · Right half-space', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:06:51.541Z'::timestamptz
    );

    -- 2026-08-17T22:08:10.241Z us #20 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '20'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '20',
      12.4, 31.9, 'LW-AT', 'Left wide · Attacking third', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:08:10.241Z'::timestamptz
    );

    -- 2026-08-17T22:14:14.440Z us #18 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '18'
    limit 1;
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '18',
      40.2, 3, 'C-6Y', 'Six-yard box · Center', 'goal',
      apid, 'pass', 8.4, 16.8, 'LW-D', 'Left wide · Top of the box',
      '2026-08-17T22:14:14.440Z'::timestamptz
    );

    -- 2026-08-17T22:20:33.190Z us #29 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '29'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '29',
      27.6, 6.3, 'C-PS', 'Box · Center', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:20:33.190Z'::timestamptz
    );

    -- 2026-08-17T22:35:36.299Z us #25 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '25'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '25',
      59, 15.9, 'RW-BOX', 'Right wide · Penalty area', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:35:36.299Z'::timestamptz
    );

    -- 2026-08-17T22:40:25.900Z us #32 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '32',
      42.6, 13.5, 'RHS-BOX', 'Box · Right half-space', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:40:25.900Z'::timestamptz
    );

    -- 2026-08-17T22:50:33.612Z us #32 Shot on Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '32',
      35.6, 10.6, 'C-PS', 'Penalty spot', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-17T22:50:33.612Z'::timestamptz
    );

    -- 2026-08-17T22:51:54.089Z us #5 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '5'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '5',
      31, 8.8, 'C-PS', 'Box · Center', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:51:54.089Z'::timestamptz
    );

    -- 2026-08-17T22:53:48.819Z us #32 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '32',
      26, 11.9, 'C-BOX', 'Box · Center', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:53:48.819Z'::timestamptz
    );

    -- 2026-08-17T22:56:33.015Z us #17 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '17'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '17',
      17.3, 22.2, 'LHS-D', 'Left half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:56:33.015Z'::timestamptz
    );

    -- 2026-08-17T22:59:18.713Z us #17 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '17'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '17',
      33.5, 14.3, 'C-BOX', 'Box · Center', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T22:59:18.713Z'::timestamptz
    );

    -- 2026-08-17T23:03:00.376Z us #5 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '5'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '5',
      50.8, 9.7, 'RHS-PS', 'Box · Right half-space', 'goal',
      apid, null, null, null, null, null,
      '2026-08-17T23:03:00.376Z'::timestamptz
    );

    -- 2026-08-17T23:09:10.225Z us #8 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '8',
      9.1, 20.3, 'LW-D', 'Left wide · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T23:09:10.225Z'::timestamptz
    );

    -- 2026-08-17T23:15:26.914Z us #8 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '8',
      57, 24.6, 'RW-D', 'Right wide · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-17T23:15:26.914Z'::timestamptz
    );
    raise notice 'Imported Morgan recorded shots';
  end if;
  gid := null;
  opp := null;

  -- ===== Olympus 2026-08-20 (30 shots) =====
  insert into public.teams (name, is_brighton) values ('Olympus', false)
  on conflict (name) do nothing;
  select id into opp from public.teams where name = 'Olympus';

  select g.id into gid from public.games g
  where g.season_id = season and g.date = '2026-08-20'
    and g.home_team_id = opp and g.away_team_id = brighton
  limit 1;
  if gid is null then
    select g.id into gid from public.games g
    where g.season_id = season and g.date = '2026-08-19'
      and g.home_team_id = opp and g.away_team_id = brighton limit 1;
  end if;
  if gid is null then
    insert into public.games (season_id, date, game_type, home_team_id, away_team_id, our_team_id)
    values (season, '2026-08-20', 'region', opp, brighton, brighton)
    returning id into gid;
  end if;

  select count(*) into n from public.shots
  where game_id = gid and created_at = '2026-08-21T03:54:28.983Z'::timestamptz;
  if n > 0 then
    raise notice 'Olympus shots already imported — skipping';
  else
    -- ensure opp #10 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '10'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '10')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #14 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '14'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '14')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #15 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '15'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '15')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #21 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '21'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '21')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #24 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '24'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '24')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #29 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '29'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '29')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #37 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '37'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '37')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #55 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '55'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '55')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;
    -- ensure opp #97 on roster
    if not exists (
      select 1 from public.rosters r
      where r.team_id = opp and r.season_id = season and r.jersey_number = '97'
    ) then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (opp, season, pid, '97')
      on conflict (team_id, season_id, jersey_number) do nothing;
    end if;

    -- 2026-08-21T01:50:05.770Z opponent #37 Shot on Goal
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '37'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '37')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '37';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '37',
      44.8, 20.6, 'RHS-D', 'Right half-space · Top of the box', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-21T01:50:05.770Z'::timestamptz
    );

    -- 2026-08-21T01:51:15.143Z us #17 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '17'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '17',
      41.4, 24.5, 'C-D', 'Zone 14', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T01:51:15.143Z'::timestamptz
    );

    -- 2026-08-21T01:53:12.805Z opponent #15 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '15'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '15')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '15';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '15',
      34, 36, 'C-HALF', 'Center · Toward halfway', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T01:53:12.805Z'::timestamptz
    );

    -- 2026-08-21T01:54:40.797Z opponent #14 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '14'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '14')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '14';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '14',
      44.7, 16.6, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T01:54:40.797Z'::timestamptz
    );

    -- 2026-08-21T02:02:13.262Z us #9 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '9'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '9',
      52.7, 24.5, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:02:13.262Z'::timestamptz
    );

    -- 2026-08-21T02:10:54.614Z us #8 Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '5'
    limit 1;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '8',
      38.7, 1.3, 'C-6Y', 'Six-yard box · Center', 'goal',
      apid, 'cross', 25.3, 1.3, 'LHS-6Y', 'Six-yard box · Left half-space',
      '2026-08-21T02:10:54.614Z'::timestamptz
    );

    -- 2026-08-21T02:12:15.921Z opponent #15 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '15'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '15')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '15';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '15',
      39.2, 20.9, 'C-D', 'Zone 14', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:12:15.921Z'::timestamptz
    );

    -- 2026-08-21T02:15:42.825Z us #32 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '32',
      18.7, 21.3, 'LHS-D', 'Left half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:15:42.825Z'::timestamptz
    );

    -- 2026-08-21T02:23:15.881Z us #8 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '8',
      49, 26.3, 'RHS-AT', 'Right half-space · Attacking third', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:23:15.881Z'::timestamptz
    );

    -- 2026-08-21T02:25:03.690Z opponent #55 Shot Blocked
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '55'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '55')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '55';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '55',
      15.1, 33.9, 'LHS-AT', 'Left half-space · Attacking third', 'blocked',
      apid, null, null, null, null, null,
      '2026-08-21T02:25:03.690Z'::timestamptz
    );

    -- 2026-08-21T02:26:38.137Z opponent #21 Shot Blocked
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '21'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '21')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '21';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '21',
      40.6, 18.8, 'C-D', 'Zone 14', 'blocked',
      apid, null, null, null, null, null,
      '2026-08-21T02:26:38.137Z'::timestamptz
    );

    -- 2026-08-21T02:26:47.954Z opponent #10 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '10'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '10')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '10';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '1', tid, pid, '10',
      25.3, 3.8, 'LHS-6Y', 'Six-yard box · Left half-space', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:26:47.954Z'::timestamptz
    );

    -- 2026-08-21T02:30:07.835Z opponent #24 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '24'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '24')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '24';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '24',
      40.2, 28.8, 'C-AT', 'Center · Attacking third', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:30:07.835Z'::timestamptz
    );

    -- 2026-08-21T02:53:22.795Z opponent #37 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '37'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '37')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '37';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '37',
      41.8, 21.1, 'C-D', 'Zone 14', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T02:53:22.795Z'::timestamptz
    );

    -- 2026-08-21T02:59:36.548Z us #13 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '13'
    limit 1;
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '13',
      43.1, 8.6, 'RHS-PS', 'Box · Right half-space', 'missed',
      apid, 'pass', 30.5, 14.5, 'C-BOX', 'Box · Center',
      '2026-08-21T02:59:36.548Z'::timestamptz
    );

    -- 2026-08-21T03:08:32.776Z us #8 Shot on Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '8',
      29.9, 2.4, 'C-6Y', 'Six-yard box · Center', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-21T03:08:32.776Z'::timestamptz
    );

    -- 2026-08-21T03:08:39.977Z us #8 Shot on Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '8'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '8',
      30.4, 0.2, 'C-6Y', 'Six-yard box · Center', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-21T03:08:39.977Z'::timestamptz
    );

    -- 2026-08-21T03:11:16.763Z opponent #10 Shot on Goal
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '10'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '10')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '10';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '10',
      25.9, 14, 'C-BOX', 'Box · Center', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-21T03:11:16.763Z'::timestamptz
    );

    -- 2026-08-21T03:13:56.070Z opponent #14 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '14'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '14')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '14';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '14',
      18.6, 8.9, 'LHS-PS', 'Box · Left half-space', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T03:13:56.070Z'::timestamptz
    );

    -- 2026-08-21T03:24:59.520Z us #26 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '26'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '26',
      30.7, 31.7, 'C-AT', 'Center · Attacking third', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T03:24:59.520Z'::timestamptz
    );

    -- 2026-08-21T03:26:23.211Z opponent #37 Goal
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '37'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '37')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '37';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '37',
      43.4, 29.2, 'RHS-AT', 'Right half-space · Attacking third', 'goal',
      apid, null, null, null, null, null,
      '2026-08-21T03:26:23.211Z'::timestamptz
    );

    -- 2026-08-21T03:27:38.509Z us #24 Missed Shot
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '24'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, '2', tid, pid, '24',
      33.6, 29, 'C-AT', 'Center · Attacking third', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T03:27:38.509Z'::timestamptz
    );

    -- 2026-08-21T03:39:27.906Z opponent #14 Shot on Goal
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '14'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '14')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '14';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '14',
      46.8, 12.9, 'RHS-BOX', 'Box · Right half-space', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-21T03:39:27.906Z'::timestamptz
    );

    -- 2026-08-21T03:41:41.935Z us #32 Shot Blocked
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '32',
      35.8, 27.5, 'C-AT', 'Center · Attacking third', 'blocked',
      apid, null, null, null, null, null,
      '2026-08-21T03:41:41.935Z'::timestamptz
    );

    -- 2026-08-21T03:41:50.752Z opponent #14 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '14'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '14')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '14';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '14',
      27, 12.9, 'C-BOX', 'Box · Center', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T03:41:50.752Z'::timestamptz
    );

    -- 2026-08-21T03:44:06.451Z opponent #15 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '15'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '15')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '15';
    end if;
    select r.player_id into apid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '29'
    limit 1;
    if apid is null then
      insert into public.players (name, short_name) values (null, null) returning id into apid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, apid, '29')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into apid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '29';
    end if;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '15',
      25, 5.4, 'LHS-6Y', 'Six-yard box · Left half-space', 'missed',
      apid, 'cross', 66.7, 1.2, 'RW-6Y', 'Right wide · Six-yard',
      '2026-08-21T03:44:06.451Z'::timestamptz
    );

    -- 2026-08-21T03:44:43.254Z us #32 Shot Blocked
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '32'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '32',
      34.8, 21, 'C-D', 'Zone 14', 'blocked',
      apid, null, null, null, null, null,
      '2026-08-21T03:44:43.254Z'::timestamptz
    );

    -- 2026-08-21T03:46:30.796Z opponent #97 Missed Shot
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '97'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '97')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '97';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '97',
      45.4, 18, 'RHS-D', 'Right half-space · Top of the box', 'missed',
      apid, null, null, null, null, null,
      '2026-08-21T03:46:30.796Z'::timestamptz
    );

    -- 2026-08-21T03:48:56.031Z us #17 Shot on Goal
    tid := brighton;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '17'
    limit 1;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET1', tid, pid, '17',
      40.7, 30.7, 'C-AT', 'Center · Attacking third', 'on-target',
      apid, null, null, null, null, null,
      '2026-08-21T03:48:56.031Z'::timestamptz
    );

    -- 2026-08-21T03:54:28.983Z opponent #15 Goal
    tid := opp;
    select r.player_id into pid from public.rosters r
    where r.team_id = tid and r.season_id = season and r.jersey_number = '15'
    limit 1;
    if pid is null then
      insert into public.players (name, short_name) values (null, null) returning id into pid;
      insert into public.rosters (team_id, season_id, player_id, jersey_number)
      values (tid, season, pid, '15')
      on conflict (team_id, season_id, jersey_number) do nothing;
      select r.player_id into pid from public.rosters r
      where r.team_id = tid and r.season_id = season and r.jersey_number = '15';
    end if;
    apid := null;
    insert into public.shots (
      game_id, period, team_id, player_id, jersey_number_at_time,
      x, y, zone_id, zone_label, result,
      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,
      created_at
    ) values (
      gid, 'ET2', tid, pid, '15',
      45.9, 47.8, 'RHS-HALF', 'Right half-space · Toward halfway', 'goal',
      apid, null, null, null, null, null,
      '2026-08-21T03:54:28.983Z'::timestamptz
    );
    raise notice 'Imported Olympus recorded shots';
  end if;
  gid := null;
  opp := null;

end;
$$;
