#!/usr/bin/env python3
"""Generate supabase/migrate_import_recorded_shots.sql from recorded data/*.csv"""
import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "supabase" / "migrate_import_recorded_shots.sql"

RESULT = {
    "Goal": "goal",
    "Shot on Goal": "on-target",
    "Shot Blocked": "blocked",
    "Missed Shot": "missed",
}
ASSIST = {"Pass": "pass", "Gap": "gap", "Cross": "cross"}


def esc(s):
    if s is None or s == "":
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def num_or_null(s):
    s = (s or "").strip()
    return "null" if s == "" else s


def read_csv(path: pathlib.Path):
    text = path.read_text(encoding="utf-8-sig")
    first = text.splitlines()[0]
    delim = "\t" if "\t" in first else ","
    rows = list(csv.DictReader(text.splitlines(), delimiter=delim))
    return [{(k or "").strip(): (v or "").strip() for k, v in r.items()} for r in rows]


FILES = [
    {
        "path": ROOT / "recorded data" / "bengals-shots-vs-morgan-2026-08-17.csv",
        "opp": "Morgan",
        "date": "2026-08-17",
        "game_type": "preseason",
        "home": "Morgan",
        "away": "Brighton",
    },
    {
        "path": ROOT / "recorded data" / "bengals-shots-vs-olympus-2026-08-19.csv",
        "opp": "Olympus",
        # Schedule + timestamps (UTC evening → MT) = 2026-08-20 away
        "date": "2026-08-20",
        "alt_dates": ["2026-08-19"],
        "game_type": "region",
        "home": "Olympus",
        "away": "Brighton",
    },
]


def main():
    lines = [
        "-- Import recorded CSV shots from recorded data/",
        "-- Generated by scripts/generate_recorded_shots_sql.py — re-run that script after CSV edits.",
        "-- Safe to re-run: skips a game if its first CSV timestamp already exists on a shot.",
        "-- Attaches to schedule games when present; otherwise creates the game.",
        "",
        "do $$",
        "declare",
        "  brighton uuid;",
        "  season uuid;",
        "  opp uuid;",
        "  gid uuid;",
        "  tid uuid;",
        "  pid uuid;",
        "  apid uuid;",
        "  n int;",
        "begin",
        "  select id into brighton from public.teams where is_brighton limit 1;",
        "  select id into season from public.seasons where label = '2026 Fall' limit 1;",
        "  if brighton is null or season is null then",
        "    raise exception 'Run schema.sql first';",
        "  end if;",
        "",
    ]

    for f in FILES:
        rows = read_csv(f["path"])
        home_is_brighton = f["home"] == "Brighton"
        lines.append(f"  -- ===== {f['opp']} {f['date']} ({len(rows)} shots) =====")
        lines.append(f"  insert into public.teams (name, is_brighton) values ({esc(f['opp'])}, false)")
        lines.append("  on conflict (name) do nothing;")
        lines.append(f"  select id into opp from public.teams where name = {esc(f['opp'])};")
        lines.append("")

        if home_is_brighton:
            home_pred = "g.home_team_id = brighton and g.away_team_id = opp"
        else:
            home_pred = "g.home_team_id = opp and g.away_team_id = brighton"

        lines.append("  select g.id into gid from public.games g")
        lines.append(f"  where g.season_id = season and g.date = {esc(f['date'])}")
        lines.append(f"    and {home_pred}")
        lines.append("  limit 1;")

        for alt in f.get("alt_dates", []):
            lines.append("  if gid is null then")
            lines.append("    select g.id into gid from public.games g")
            lines.append(f"    where g.season_id = season and g.date = {esc(alt)}")
            lines.append(f"      and {home_pred} limit 1;")
            lines.append("  end if;")

        lines.append("  if gid is null then")
        if home_is_brighton:
            lines.append(
                "    insert into public.games (season_id, date, game_type, home_team_id, away_team_id, our_team_id)"
            )
            lines.append(
                f"    values (season, {esc(f['date'])}, {esc(f['game_type'])}, brighton, opp, brighton)"
            )
        else:
            lines.append(
                "    insert into public.games (season_id, date, game_type, home_team_id, away_team_id, our_team_id)"
            )
            lines.append(
                f"    values (season, {esc(f['date'])}, {esc(f['game_type'])}, opp, brighton, brighton)"
            )
        lines.append("    returning id into gid;")
        lines.append("  end if;")
        lines.append("")

        times = [r["time"] for r in rows if r.get("time")]
        lines.append("  select count(*) into n from public.shots")
        lines.append(f"  where game_id = gid and created_at = {esc(times[0])}::timestamptz;")
        lines.append("  if n > 0 then")
        lines.append(f"    raise notice '{f['opp']} shots already imported — skipping';")
        lines.append("  else")

        opp_nums = {
            r["player_number"]
            for r in rows
            if r.get("team") == "opponent" and r.get("player_number")
        }
        assist_opp = {
            r["assisted_by_number"]
            for r in rows
            if r.get("team") == "opponent" and r.get("assisted_by_number")
        }
        for num in sorted(opp_nums | assist_opp, key=lambda x: (len(x), x)):
            lines.append(f"    -- ensure opp #{num} on roster")
            lines.append("    if not exists (")
            lines.append("      select 1 from public.rosters r")
            lines.append(
                f"      where r.team_id = opp and r.season_id = season and r.jersey_number = {esc(num)}"
            )
            lines.append("    ) then")
            lines.append(
                "      insert into public.players (name, short_name) values (null, null) returning id into pid;"
            )
            lines.append(
                "      insert into public.rosters (team_id, season_id, player_id, jersey_number)"
            )
            lines.append(f"      values (opp, season, pid, {esc(num)})")
            lines.append("      on conflict (team_id, season_id, jersey_number) do nothing;")
            lines.append("    end if;")

        for r in reversed(rows):
            result = RESULT.get(r.get("result", ""))
            if not result:
                raise SystemExit(f"Unknown result {r.get('result')!r} in {f['path']}")
            period = r.get("half") or "1"
            if period not in ("1", "2", "ET1", "ET2"):
                raise SystemExit(f"bad period {period}")
            is_us = r.get("team") == "us"
            team_expr = "brighton" if is_us else "opp"
            jersey = r.get("player_number") or ""
            assist_jersey = r.get("assisted_by_number") or ""
            assist_type = ASSIST.get(r.get("assist_type", "")) if r.get("assist_type") else None

            lines.append("")
            lines.append(f"    -- {r.get('time')} {r.get('team')} #{jersey} {r.get('result')}")
            lines.append(f"    tid := {team_expr};")
            if jersey:
                lines.append("    select r.player_id into pid from public.rosters r")
                lines.append(
                    f"    where r.team_id = tid and r.season_id = season and r.jersey_number = {esc(jersey)}"
                )
                lines.append("    limit 1;")
                if not is_us:
                    lines.append("    if pid is null then")
                    lines.append(
                        "      insert into public.players (name, short_name) values (null, null) returning id into pid;"
                    )
                    lines.append(
                        "      insert into public.rosters (team_id, season_id, player_id, jersey_number)"
                    )
                    lines.append(f"      values (tid, season, pid, {esc(jersey)})")
                    lines.append("      on conflict (team_id, season_id, jersey_number) do nothing;")
                    lines.append("      select r.player_id into pid from public.rosters r")
                    lines.append(
                        f"      where r.team_id = tid and r.season_id = season and r.jersey_number = {esc(jersey)};"
                    )
                    lines.append("    end if;")
            else:
                lines.append("    pid := null;")

            if assist_jersey and assist_type:
                lines.append("    select r.player_id into apid from public.rosters r")
                lines.append(
                    f"    where r.team_id = tid and r.season_id = season and r.jersey_number = {esc(assist_jersey)}"
                )
                lines.append("    limit 1;")
                if not is_us:
                    lines.append("    if apid is null then")
                    lines.append(
                        "      insert into public.players (name, short_name) values (null, null) returning id into apid;"
                    )
                    lines.append(
                        "      insert into public.rosters (team_id, season_id, player_id, jersey_number)"
                    )
                    lines.append(f"      values (tid, season, apid, {esc(assist_jersey)})")
                    lines.append("      on conflict (team_id, season_id, jersey_number) do nothing;")
                    lines.append("      select r.player_id into apid from public.rosters r")
                    lines.append(
                        f"      where r.team_id = tid and r.season_id = season and r.jersey_number = {esc(assist_jersey)};"
                    )
                    lines.append("    end if;")
            else:
                lines.append("    apid := null;")

            ax = num_or_null(r.get("assist_x"))
            ay = num_or_null(r.get("assist_y"))
            azid = esc(r.get("assist_zone_id")) if r.get("assist_zone_id") else "null"
            azlab = esc(r.get("assist_zone")) if r.get("assist_zone") else "null"
            atype = esc(assist_type) if assist_type else "null"
            jersql = esc(jersey) if jersey else "null"

            lines.append("    insert into public.shots (")
            lines.append("      game_id, period, team_id, player_id, jersey_number_at_time,")
            lines.append("      x, y, zone_id, zone_label, result,")
            lines.append(
                "      assist_player_id, assist_type, assist_x, assist_y, assist_zone_id, assist_zone_label,"
            )
            lines.append("      created_at")
            lines.append("    ) values (")
            lines.append(f"      gid, {esc(period)}, tid, pid, {jersql},")
            lines.append(
                f"      {num_or_null(r.get('shot_x'))}, {num_or_null(r.get('shot_y'))}, {esc(r.get('shot_zone_id'))}, {esc(r.get('shot_zone'))}, {esc(result)},"
            )
            lines.append(f"      apid, {atype}, {ax}, {ay}, {azid}, {azlab},")
            lines.append(f"      {esc(r.get('time'))}::timestamptz")
            lines.append("    );")

        lines.append(f"    raise notice 'Imported {f['opp']} recorded shots';")
        lines.append("  end if;")
        lines.append("  gid := null;")
        lines.append("  opp := null;")
        lines.append("")

    lines.append("end;")
    lines.append("$$;")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
